SELECT 
DATA.ID,
CASE WHEN DATA.NUM > (SELECT COUNT(*) FROM ECOLI_DATA)*0.75 THEN 'CRITICAL'
     WHEN DATA.NUM > (SELECT COUNT(*) FROM ECOLI_DATA)*0.50 THEN 'HIGH'
     WHEN DATA.NUM > (SELECT COUNT(*) FROM ECOLI_DATA)*0.25 THEN 'MEDIUM'
     ELSE 'LOW'
     END AS COLONY_NAME
FROM
(
SELECT
ID,
SIZE_OF_COLONY,
ROW_NUMBER() OVER (ORDER BY SIZE_OF_COLONY) AS NUM
FROM
ECOLI_DATA
ORDER BY SIZE_OF_COLONY DESC
) 
DATA
ORDER BY DATA.ID