SELECT
    INFO.ID,
    NAME.FISH_NAME,
    INFO.LENGTH
FROM FISH_INFO AS INFO
JOIN FISH_NAME_INFO AS NAME
    ON INFO.FISH_TYPE = NAME.FISH_TYPE
JOIN (
    SELECT
        FISH_TYPE,
        MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) AS MX
    ON INFO.FISH_TYPE = MX.FISH_TYPE
   AND INFO.LENGTH = MX.MAX_LENGTH
ORDER BY
    INFO.ID ASC;
